import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import React from "react";
import Footer from "./components/Footer";

// --- استورد مكونات النافبار والفوتر ---
// import Navbar from "@/components/Navbar"; // مثال: افترض أن لديك مكون نافبار
// import Footer from "@/components/Footer"; // مثال: افترض أن لديك مكون فوتر

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 1. أضفنا الكلاسات إلى الـ body مباشرة */}
      <body
        className={`${geistSans.variable} flex flex-col min-h-screen antialiased`}
      >


        {/* 2. أنشأنا وسم <main> للمحتوى الرئيسي */}
        <main className="flex-grow">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
